name: Jenga APK ya Java

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vuta kodi kutoka GitHub
        uses: actions/checkout@v4

      - name: Weka Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Weka Mtambo wa Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Fua APK ya Release
        run: gradle assembleRelease

      - name: Toa APK kwa Albert
        uses: actions/upload-artifact@v4
        with:
          name: wsendy-java-apk
          path: "**/build/outputs/apk/release/*.apk"
